name: Android Build
on:
  push:
    branches: ['master']
  pull_request:
      branches: ['master']
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/checkout@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Make script executable
        run: chmod +x ./scripts/your-script.sh
      - name: Build Project
        run: ./gradlew assembleDebug
      - name: Run unit test
        run: ./gradlew testDebugUnitTest
